packages:
  - apps/*
  - packages/*

autoInstallPeers: true
engineStrict: true
pmOnFail: error
saveExact: true
strictPeerDependencies: true

overrides:
  '@expo/plist>@xmldom/xmldom': 0.8.15
  'plist>@xmldom/xmldom': 0.9.12
  'fast-uri@3': 3.1.7
  'fast-uri@4': 4.1.4
  react: 19.2.3
  react-dom: 19.2.3

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.22'
  - expo@57.0.20
  - expo-build-properties@57.0.17
  - expo-modules-core@57.0.16
  - expo-modules-jsi@57.0.8
  - expo-notifications@57.0.17
  - fast-uri@3.1.7
  - fast-uri@4.1.4

supportedArchitectures:
  os: [current, darwin, linux]
  cpu: [current, arm64, x64]
  libc: [current, glibc, musl]

allowBuilds:
  esbuild: true
  sharp: true
