export {
  AccountConflictError,
  AccountNotFoundError,
  type AuthenticatedSession,
  type ConfirmEmailVerificationTokenInput,
  type ConfirmPasswordRecoveryTokenInput,
  type CreateSessionInput,
  confirmEmailVerificationToken,
  confirmPasswordRecoveryToken,
  createSession,
  EmailVerificationTokenExpiredError,
  EmailVerificationTokenInvalidError,
  findActiveSessionByTokenHash,
  findPasswordCredentialByEmail,
  findPendingErasureRecoverySessionByTokenHash,
  getUserProfile,
  type IssueEmailVerificationTokenInput,
  type IssueEmailVerificationTokenResult,
  type IssuePasswordRecoveryTokenInput,
  type IssuePasswordRecoveryTokenResult,
  issueEmailVerificationToken,
  issuePasswordRecoveryToken,
  type PasswordCredentialRecord,
  PasswordCredentialStaleError,
  PasswordRecoveryTokenExpiredError,
  PasswordRecoveryTokenInvalidError,
  type PendingErasureRecoverySession,
  ProfileRevisionConflictError,
  type RegisterPasswordAccountInput,
  registerPasswordAccount,
  revokeSession,
  type SessionRecord,
  type UpdateUserProfileInput,
  type UserProfileRecord,
  updateUserProfile,
} from "./accounts.js";
export {
  assertCatalogueAuthorityCanaryEvidence,
  assertCatalogueAuthorityDeploymentEvidence,
  CATALOGUE_ACTIVATION_AUTHORITY_CONSTRAINT_DEFINITION,
  CATALOGUE_ACTIVATION_GUARD_SOURCE_SHA256,
  CATALOGUE_APPROVAL_FUNCTION_SOURCE_SHA256,
  CATALOGUE_APPROVAL_GUARD_SOURCE_SHA256,
  CATALOGUE_APPROVAL_V1_FUNCTION_SOURCE_SHA256,
  CATALOGUE_AUTHORITY_CONSTRAINT_POLICY,
  CATALOGUE_AUTHORITY_FROZEN_COLUMN_POLICY,
  CATALOGUE_AUTHORITY_FUNCTION_POLICY,
  CATALOGUE_AUTHORITY_INDEX_POLICY,
  CATALOGUE_AUTHORITY_PROTECTED_TABLES,
  CATALOGUE_AUTHORITY_TRIGGER_POLICY,
  CATALOGUE_BATCH_NUTRITION_SEMANTIC_CONSTRAINT_DEFINITION,
  CATALOGUE_BATCH_NUTRITION_SEMANTIC_GUARD_SOURCE_SHA256,
  CATALOGUE_CAPABILITY_ROLES,
  CATALOGUE_CHECKPOINT_STAGING_SEAL_GUARD_SOURCE_SHA256,
  CATALOGUE_COMPUTE_STAGING_SEAL_FUNCTION_SOURCE_SHA256,
  CATALOGUE_NUTRITION_ATTESTATION_FUNCTION_SOURCE_SHA256,
  CATALOGUE_NUTRITION_COMPUTE_RECORD_FUNCTION_SOURCE_SHA256,
  CATALOGUE_NUTRITION_DECIMAL_PRODUCT_FUNCTION_SOURCE_SHA256,
  CATALOGUE_NUTRITION_UTF16_LENGTH_FUNCTION_SOURCE_SHA256,
  CATALOGUE_OBSERVE_VALIDATION_FUNCTION_SOURCE_SHA256,
  CATALOGUE_PROMOTION_FUNCTION_SOURCE_SHA256,
  CATALOGUE_PROMOTION_V1_FUNCTION_SOURCE_SHA256,
  CATALOGUE_RECORD_NUTRITION_SEMANTIC_CONSTRAINT_DEFINITION,
  CATALOGUE_RECORD_NUTRITION_SEMANTIC_GUARD_SOURCE_SHA256,
  CATALOGUE_RECORD_STAGING_SEAL_GUARD_SOURCE_SHA256,
  CATALOGUE_REVIEWER_CAPABILITIES,
  CATALOGUE_ROLLBACK_FUNCTION_SOURCE_SHA256,
  CATALOGUE_ROLLBACK_V1_FUNCTION_SOURCE_SHA256,
  CATALOGUE_STAGE_BATCH_FUNCTION_SOURCE_SHA256,
  CATALOGUE_STAGE_PARSER_REPORT_FUNCTION_SOURCE_SHA256,
  CATALOGUE_STAGE_RECORD_CHUNK_FUNCTION_SOURCE_SHA256,
  CATALOGUE_STAGE_VALIDATE_AUTHORITY_CONSTRAINT_DEFINITION,
  CATALOGUE_STAGE_VALIDATE_GUARD_SOURCE_SHA256,
  CATALOGUE_STAGING_SEAL_CONSTRAINT_DEFINITION,
  CATALOGUE_VALIDATE_BATCH_FUNCTION_SOURCE_SHA256,
  CATALOGUE_VALIDATE_BATCH_V1_FUNCTION_SOURCE_SHA256,
  type CatalogueAclEvidence,
  type CatalogueAuthorityCanaryEvidence,
  type CatalogueAuthorityCanaryName,
  type CatalogueAuthorityConstraintEvidence,
  type CatalogueAuthorityDeploymentEvidence,
  type CatalogueAuthorityDeploymentPolicy,
  type CatalogueAuthorityFrozenColumnEvidence,
  type CatalogueAuthorityFunctionPolicy,
  type CatalogueAuthorityIndexEvidence,
  type CatalogueAuthorityTriggerPolicy,
  type CatalogueCapabilityRole,
  type CatalogueCapabilityRoleEvidence,
  type CatalogueColumnAclEvidence,
  type CatalogueDefaultAclEvidence,
  type CatalogueFunctionEvidence,
  type CatalogueFunctionExecuteGrantees,
  type CatalogueLoginEvidence,
  type CatalogueNonReviewerClass,
  type CatalogueRelationEvidence,
  type CatalogueReviewerClass,
  type CatalogueRoleMembershipEvidence,
  type CatalogueTriggerEvidence,
  type CatalogueTypeEvidence,
  catalogueAuthorityDeploymentPolicySha256,
  catalogueAuthorityDeploymentStructureSha256,
  parseCatalogueAuthorityDeploymentPolicy,
} from "./catalogue-authority-deployment.js";
export {
  type CatalogueAuthorityCanaryConnections,
  collectCatalogueAuthorityDeploymentEvidence,
  runCatalogueReviewerCanaries,
} from "./catalogue-authority-deployment-runtime.js";
export {
  type ApproveBatchInput,
  approveBatch,
  type BatchCheckpoint,
  type BatchPolicyEvaluation,
  type BatchRecordValidation,
  type BatchValidationPolicy,
  type BatchValidationSummary,
  evaluateBatchPolicy,
  getBatchCheckpoint,
  getSourceNutrientMappingDigest,
  type ParserCountEvidence,
  type PromoteBatchOptions,
  type PromoteBatchResult,
  previewBatchValidation,
  promoteBatch,
  type ReconcileCatalogueBatchInput,
  type RecordBatchParserReportAndValidateResult,
  type RecordBatchParserReportInput,
  type RegisterFoodSourceInput,
  type RegisterSourceNutrientMappingsInput,
  type RollbackSourceReleaseInput,
  type RollbackSourceReleaseResult,
  reconcileCatalogueBatch,
  recordBatchParserReport,
  recordBatchParserReportAndValidate,
  registerFoodSourceFromReviewedManifest,
  registerSourceNutrientMappings,
  rollbackSourceRelease,
  type SaveBatchCheckpointInput,
  type StageBatchInput,
  type StageBatchRecordsResult,
  type StageBatchResult,
  type StagedCatalogueRecordInput,
  type SupersedeSourceNutrientMappingInput,
  saveBatchCheckpoint,
  stageBatch,
  stageBatchRecords,
  supersedeSourceNutrientMapping,
  validateBatch,
  verifyCnfParserReport,
} from "./catalogue-ingestion.js";
export {
  buildCatalogueReconciliationDocument,
  type CatalogueReconciliationBuildInput,
  type CatalogueReconciliationCandidateCounts,
  type CatalogueReconciliationCandidateEvidence,
  type CatalogueReconciliationDocument,
  type CatalogueReconciliationFoodSnapshot,
  type CatalogueReconciliationMappingSnapshot,
  type CatalogueReconciliationNutrientSnapshot,
  type CatalogueReconciliationQuarantinedRecord,
  type CatalogueReconciliationRejectedBarcode,
  type CatalogueReconciliationReleaseEvidence,
  type CatalogueReconciliationServingSnapshot,
  verifyCatalogueReconciliationDocument,
} from "./catalogue-reconciliation.js";
export {
  type CatalogueBarcodeEvidence,
  type CatalogueRecordValidationContext,
  type CatalogueRecordValidationResult,
  type CatalogueValidationDisposition,
  type CatalogueValidationIssue,
  type CatalogueValidationIssueSeverity,
  canonicalJson,
  canonicalJsonChunks,
  type ReviewedCatalogueNutrientMapping,
  readCatalogueBarcodeEvidence,
  sha256CanonicalJson,
  validateCatalogueRecord,
} from "./catalogue-validation.js";
export {
  assertDatabaseMigrationLedgerReady,
  assertDatabaseReady,
  createDatabase,
  createDatabaseFromEnvironment,
  type DatabaseClientOptions,
  hasDatabaseTlsQueryParameter,
} from "./client.js";
export {
  type CreateFoodDiaryEntryInput,
  type CreateRecipeDiaryEntryInput,
  createFoodDiaryEntry,
  createRecipeDiaryEntry,
  type DeleteDiaryEntryInput,
  type DiaryDayPageRecord,
  type DiaryDayRecord,
  type DiaryDayRevisionRecord,
  type DiaryEntryRecord,
  DiaryEntryRevisionConflictError,
  type DiaryFoodEntryRecord,
  type DiaryFoodMutationResult,
  DiaryIdempotencyConflictError,
  DiaryLockedError,
  type DiaryMealSlot,
  type DiaryMutationResult,
  DiaryNotFoundError,
  type DiaryNutrientAggregateRecord,
  type DiaryPageContinuationRecord,
  DiaryPageStaleError,
  DiaryPersistenceError,
  type DiaryPersistenceErrorCode,
  type DiaryPortionInput,
  type DiaryRecipeEntryRecord,
  type DiaryRecipeMutationResult,
  DiaryTimeZoneChangedError,
  DiaryValidationError,
  deleteDiaryEntry,
  getDiaryDay,
  getDiaryDayPage,
  type RepeatDiaryEntryInput,
  repeatDiaryEntry,
  type UpdateDiaryEntryInput,
  type UpdateFoodDiaryEntryInput,
  type UpdateRecipeDiaryEntryInput,
  updateDiaryEntry,
  updateFoodDiaryEntry,
  updateRecipeDiaryEntry,
} from "./diary.js";
export {
  assertFoodSearchProjectionRevision,
  type ConsumeFoodSearchProjectionSnapshotOptions,
  consumeFoodSearchProjectionSnapshot,
  type FoodSearchBarcodeProjection,
  type FoodSearchFallbackResult,
  type FoodSearchProjectionDocument,
  type FoodSearchProjectionPage,
  type FoodSearchProjectionPublicationState,
  FoodSearchProjectionRevisionChangedError,
  type FoodSearchProjectionSnapshotInfo,
  type FoodSearchProjectionSnapshotPage,
  type FoodSearchProjectionSnapshotResult,
  type FoodSearchServingProjection,
  getFoodSearchProjectionPublicationState,
  isValidGtin,
  type LookupPromotedFoodByBarcodeInput,
  lookupPromotedFoodByBarcode,
  normalizeGtin14,
  type PageFoodSearchProjectionInput,
  pageFoodSearchProjection,
  publishFoodSearchProjectionRevision,
  type SearchPromotedFoodsPostgresInput,
  searchPromotedFoodsPostgres,
} from "./food-search.js";
export {
  type ClaimedFoodSearchRebuildEvent,
  type ClaimFoodSearchRebuildEventInput,
  type ClaimFoodSearchRebuildEventsInput,
  claimFoodSearchRebuildEvent,
  claimFoodSearchRebuildEvents,
  type FoodSearchRebuildLockResult,
  type MarkFoodSearchRebuildEventPublishedInput,
  type MarkFoodSearchRebuildEventsPublishedInput,
  markFoodSearchRebuildEventPublished,
  markFoodSearchRebuildEventsPublished,
  type PublishFoodSearchProjectionAndAcknowledgeEventsInput,
  publishFoodSearchProjectionAndAcknowledgeEvents,
  type ReleasedFoodSearchRebuildEvent,
  type ReleasedFoodSearchRebuildEventResult,
  type ReleaseFoodSearchRebuildEventInput,
  type ReleaseFoodSearchRebuildEventsInput,
  releaseFoodSearchRebuildEvent,
  releaseFoodSearchRebuildEvents,
  withFoodSearchRebuildLock,
} from "./food-search-outbox.js";
export {
  type CreateNutritionGoalInput,
  createNutritionGoal,
  type GoalActivityLevelCode,
  type GoalNutrientDefinitionRecord,
  getCurrentNutritionGoal,
  getNutritionGoal,
  getNutritionGoalProgress,
  listReferenceTargetSets,
  listTargetableNutrients,
  type NutritionGoalDraft,
  type NutritionGoalEnergyInput,
  type NutritionGoalEnergyProgressRecord,
  type NutritionGoalEnergyRecord,
  NutritionGoalIdempotencyConflictError,
  type NutritionGoalMutationResult,
  NutritionGoalNotFoundError,
  NutritionGoalPeriodConflictError,
  NutritionGoalPersistedIntegrityError,
  NutritionGoalPersistenceError,
  type NutritionGoalPersistenceErrorCode,
  NutritionGoalProfileRevisionConflictError,
  type NutritionGoalProgressRecord,
  type NutritionGoalRecord,
  type NutritionGoalReferenceInput,
  type NutritionGoalReferenceRecord,
  NutritionGoalReferenceUnavailableError,
  NutritionGoalRevisionConflictError,
  type NutritionGoalTargetInput,
  type NutritionGoalTargetProgressRecord,
  type NutritionGoalTargetRecord,
  NutritionGoalUnsupportedProfileError,
  NutritionGoalValidationError,
  type NutritionGoalVersionRecord,
  type ReferenceTargetSetListRecord,
  type ReviseNutritionGoalInput,
  reviseNutritionGoal,
} from "./goals.js";
export {
  type CreateHydrationEntryInput,
  createHydrationEntry,
  type DeleteHydrationEntryInput,
  deleteHydrationEntry,
  type GetHydrationDayInput,
  getHydrationDay,
  type HydrationDayRecord,
  type HydrationDayRevisionRecord,
  type HydrationEntryRecord,
  HydrationEntryRevisionConflictError,
  HydrationIdempotencyConflictError,
  type HydrationMutationResult,
  HydrationNotFoundError,
  HydrationPersistenceError,
  type HydrationPersistenceErrorCode,
  HydrationTimeZoneChangedError,
  HydrationValidationError,
  type UpdateHydrationEntryInput,
  updateHydrationEntry,
} from "./hydration.js";
export {
  type AppliedMigration,
  discoverMigrations,
  type MigrationResult,
  runMigrations,
} from "./migrator.js";
export {
  type CreateRecipeInput,
  createRecipe,
  getRecipe,
  listRecipes,
  RecipeCursorError,
  type RecipeDraft,
  RecipeIdempotencyConflictError,
  type RecipeIngredientInput,
  type RecipeIngredientRecord,
  type RecipeListRecord,
  type RecipeMutationResult,
  RecipeNotFoundError,
  RecipePersistenceError,
  type RecipePersistenceErrorCode,
  type RecipeRecord,
  RecipeRevisionConflictError,
  type RecipeSourceRecord,
  RecipeValidationError,
  type RecipeVersionRecord,
  type RecipeWarningRecord,
  type RecipeYieldInput,
  type ReviseRecipeInput,
  reviseRecipe,
} from "./recipes.js";
export {
  assertReferenceSourcesHttps,
  assertReferenceTargetSelection,
  REFERENCE_TARGET_ACKNOWLEDGEMENT_POLICY_CODE,
  REFERENCE_TARGET_ACKNOWLEDGEMENT_POLICY_VERSION,
  REFERENCE_TARGET_ACKNOWLEDGEMENT_TEXT,
  REFERENCE_TARGET_CAUTIONS,
  REFERENCE_TARGET_NOTICE,
  REFERENCE_TARGET_SOURCES,
  REFERENCE_TARGET_TEMPLATE_CODE,
  REFERENCE_TARGET_TEMPLATE_VERSION,
  type ReferenceTargetAvailabilityReasonCode,
  type ReferenceTargetGroupCode,
  type ReferenceTargetPolicyRow,
  type ReferenceTargetSelectionInput,
  referenceEligibleThroughExclusive,
  referenceSourceRows,
  referenceTargetPolicy,
} from "./reference-targets.js";
export {
  assertDatabaseRestoreReplayReady,
  type CompleteDatabaseRestoreReplayAttestationInput,
  completeDatabaseRestoreReplayAttestation,
  type DatabaseRestoreAttestationRecord,
} from "./restore.js";
export * from "./retention.js";
export type * from "./types.js";
