export {
  AccountConflictError,
  AccountNotFoundError,
  type AuthenticatedSession,
  type ConfirmEmailVerificationTokenInput,
  type ConfirmPasswordRecoveryTokenInput,
  type CreateSessionInput,
  confirmEmailVerificationToken,
  confirmPasswordRecoveryToken,
  createSession,
  EmailVerificationTokenExpiredError,
  EmailVerificationTokenInvalidError,
  findActiveSessionByTokenHash,
  findPasswordCredentialByEmail,
  findPendingErasureRecoverySessionByTokenHash,
  getUserProfile,
  type IssueEmailVerificationTokenInput,
  type IssueEmailVerificationTokenResult,
  type IssuePasswordRecoveryTokenInput,
  type IssuePasswordRecoveryTokenResult,
  issueEmailVerificationToken,
  issuePasswordRecoveryToken,
  type PasswordCredentialRecord,
  PasswordCredentialStaleError,
  PasswordRecoveryTokenExpiredError,
  PasswordRecoveryTokenInvalidError,
  type PendingErasureRecoverySession,
  ProfileRevisionConflictError,
  type RegisterPasswordAccountInput,
  registerPasswordAccount,
  revokeSession,
  type SessionRecord,
  type UpdateUserProfileInput,
  type UserProfileRecord,
  updateUserProfile,
} from "./accounts.js";
export {
  type ApproveBatchInput,
  approveBatch,
  type BatchCheckpoint,
  type BatchPolicyEvaluation,
  type BatchRecordValidation,
  type BatchValidationPolicy,
  type BatchValidationSummary,
  evaluateBatchPolicy,
  getBatchCheckpoint,
  getSourceNutrientMappingDigest,
  type ParserCountEvidence,
  type PromoteBatchOptions,
  type PromoteBatchResult,
  previewBatchValidation,
  promoteBatch,
  type ReconcileCatalogueBatchInput,
  type RecordBatchParserReportAndValidateResult,
  type RecordBatchParserReportInput,
  type RegisterFoodSourceInput,
  type RegisterSourceNutrientMappingsInput,
  type RollbackSourceReleaseInput,
  type RollbackSourceReleaseResult,
  reconcileCatalogueBatch,
  recordBatchParserReport,
  recordBatchParserReportAndValidate,
  registerFoodSourceFromReviewedManifest,
  registerSourceNutrientMappings,
  rollbackSourceRelease,
  type SaveBatchCheckpointInput,
  type StageBatchInput,
  type StageBatchRecordsResult,
  type StageBatchResult,
  type StagedCatalogueRecordInput,
  type SupersedeSourceNutrientMappingInput,
  saveBatchCheckpoint,
  stageBatch,
  stageBatchRecords,
  supersedeSourceNutrientMapping,
  validateBatch,
  verifyCnfParserReport,
} from "./catalogue-ingestion.js";
export {
  buildCatalogueReconciliationDocument,
  type CatalogueReconciliationBuildInput,
  type CatalogueReconciliationCandidateCounts,
  type CatalogueReconciliationCandidateEvidence,
  type CatalogueReconciliationDocument,
  type CatalogueReconciliationFoodSnapshot,
  type CatalogueReconciliationMappingSnapshot,
  type CatalogueReconciliationNutrientSnapshot,
  type CatalogueReconciliationQuarantinedRecord,
  type CatalogueReconciliationRejectedBarcode,
  type CatalogueReconciliationReleaseEvidence,
  type CatalogueReconciliationServingSnapshot,
  verifyCatalogueReconciliationDocument,
} from "./catalogue-reconciliation.js";
export {
  type CatalogueBarcodeEvidence,
  type CatalogueRecordValidationContext,
  type CatalogueRecordValidationResult,
  type CatalogueValidationDisposition,
  type CatalogueValidationIssue,
  type CatalogueValidationIssueSeverity,
  canonicalJson,
  canonicalJsonChunks,
  type ReviewedCatalogueNutrientMapping,
  readCatalogueBarcodeEvidence,
  sha256CanonicalJson,
  validateCatalogueRecord,
} from "./catalogue-validation.js";
export {
  assertDatabaseMigrationLedgerReady,
  assertDatabaseReady,
  createDatabase,
  createDatabaseFromEnvironment,
  type DatabaseClientOptions,
  hasDatabaseTlsQueryParameter,
} from "./client.js";
export {
  type CreateFoodDiaryEntryInput,
  type CreateRecipeDiaryEntryInput,
  createFoodDiaryEntry,
  createRecipeDiaryEntry,
  type DeleteDiaryEntryInput,
  type DiaryDayPageRecord,
  type DiaryDayRecord,
  type DiaryDayRevisionRecord,
  type DiaryEntryRecord,
  DiaryEntryRevisionConflictError,
  type DiaryFoodEntryRecord,
  type DiaryFoodMutationResult,
  DiaryIdempotencyConflictError,
  DiaryLockedError,
  type DiaryMealSlot,
  type DiaryMutationResult,
  DiaryNotFoundError,
  type DiaryNutrientAggregateRecord,
  type DiaryPageContinuationRecord,
  DiaryPageStaleError,
  DiaryPersistenceError,
  type DiaryPersistenceErrorCode,
  type DiaryPortionInput,
  type DiaryRecipeEntryRecord,
  type DiaryRecipeMutationResult,
  DiaryTimeZoneChangedError,
  DiaryValidationError,
  deleteDiaryEntry,
  getDiaryDay,
  getDiaryDayPage,
  type RepeatDiaryEntryInput,
  repeatDiaryEntry,
  type UpdateDiaryEntryInput,
  type UpdateFoodDiaryEntryInput,
  type UpdateRecipeDiaryEntryInput,
  updateDiaryEntry,
  updateFoodDiaryEntry,
  updateRecipeDiaryEntry,
} from "./diary.js";
export {
  assertFoodSearchProjectionRevision,
  type ConsumeFoodSearchProjectionSnapshotOptions,
  consumeFoodSearchProjectionSnapshot,
  type FoodSearchBarcodeProjection,
  type FoodSearchFallbackResult,
  type FoodSearchProjectionDocument,
  type FoodSearchProjectionPage,
  type FoodSearchProjectionPublicationState,
  FoodSearchProjectionRevisionChangedError,
  type FoodSearchProjectionSnapshotInfo,
  type FoodSearchProjectionSnapshotPage,
  type FoodSearchProjectionSnapshotResult,
  type FoodSearchServingProjection,
  getFoodSearchProjectionPublicationState,
  isValidGtin,
  type LookupPromotedFoodByBarcodeInput,
  lookupPromotedFoodByBarcode,
  normalizeGtin14,
  type PageFoodSearchProjectionInput,
  pageFoodSearchProjection,
  publishFoodSearchProjectionRevision,
  type SearchPromotedFoodsPostgresInput,
  searchPromotedFoodsPostgres,
} from "./food-search.js";
export {
  type ClaimedFoodSearchRebuildEvent,
  type ClaimFoodSearchRebuildEventInput,
  type ClaimFoodSearchRebuildEventsInput,
  claimFoodSearchRebuildEvent,
  claimFoodSearchRebuildEvents,
  type FoodSearchRebuildLockResult,
  type MarkFoodSearchRebuildEventPublishedInput,
  type MarkFoodSearchRebuildEventsPublishedInput,
  markFoodSearchRebuildEventPublished,
  markFoodSearchRebuildEventsPublished,
  type PublishFoodSearchProjectionAndAcknowledgeEventsInput,
  publishFoodSearchProjectionAndAcknowledgeEvents,
  type ReleasedFoodSearchRebuildEvent,
  type ReleasedFoodSearchRebuildEventResult,
  type ReleaseFoodSearchRebuildEventInput,
  type ReleaseFoodSearchRebuildEventsInput,
  releaseFoodSearchRebuildEvent,
  releaseFoodSearchRebuildEvents,
  withFoodSearchRebuildLock,
} from "./food-search-outbox.js";
export {
  type CreateNutritionGoalInput,
  createNutritionGoal,
  type GoalActivityLevelCode,
  type GoalNutrientDefinitionRecord,
  getCurrentNutritionGoal,
  getNutritionGoal,
  getNutritionGoalProgress,
  listTargetableNutrients,
  type NutritionGoalDraft,
  type NutritionGoalEnergyInput,
  type NutritionGoalEnergyProgressRecord,
  type NutritionGoalEnergyRecord,
  NutritionGoalIdempotencyConflictError,
  type NutritionGoalMutationResult,
  NutritionGoalNotFoundError,
  NutritionGoalPeriodConflictError,
  NutritionGoalPersistenceError,
  type NutritionGoalPersistenceErrorCode,
  type NutritionGoalProgressRecord,
  type NutritionGoalRecord,
  NutritionGoalRevisionConflictError,
  type NutritionGoalTargetInput,
  type NutritionGoalTargetProgressRecord,
  type NutritionGoalTargetRecord,
  NutritionGoalUnsupportedProfileError,
  NutritionGoalValidationError,
  type NutritionGoalVersionRecord,
  type ReviseNutritionGoalInput,
  reviseNutritionGoal,
} from "./goals.js";
export {
  type AppliedMigration,
  discoverMigrations,
  type MigrationResult,
  runMigrations,
} from "./migrator.js";
export {
  type CreateRecipeInput,
  createRecipe,
  getRecipe,
  listRecipes,
  RecipeCursorError,
  type RecipeDraft,
  RecipeIdempotencyConflictError,
  type RecipeIngredientInput,
  type RecipeIngredientRecord,
  type RecipeListRecord,
  type RecipeMutationResult,
  RecipeNotFoundError,
  RecipePersistenceError,
  type RecipePersistenceErrorCode,
  type RecipeRecord,
  RecipeRevisionConflictError,
  type RecipeSourceRecord,
  RecipeValidationError,
  type RecipeVersionRecord,
  type RecipeWarningRecord,
  type RecipeYieldInput,
  type ReviseRecipeInput,
  reviseRecipe,
} from "./recipes.js";
export {
  assertDatabaseRestoreReplayReady,
  type CompleteDatabaseRestoreReplayAttestationInput,
  completeDatabaseRestoreReplayAttestation,
  type DatabaseRestoreAttestationRecord,
} from "./restore.js";
export * from "./retention.js";
export type * from "./types.js";
