packages:
  - .

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
strictPeerDependencies: true
verifyDepsBeforeRun: error
ignoreScripts: true
saveExact: true
registry: https://registry.npmjs.org/
